language: common-lisp
sudo: false

notifications:
  irc:
    channels:
      - "chat.freenode.net##ht"
    on_success: change
    on_failure: always
    template:
      - "%{repository_slug} (%{branch}:%{commit}) : %{commit_message}"
      - "Result: %{result} Details: %{build_url}"

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  global:
    - PATH=$HOME/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t/
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=cmucl
    - LISP=alisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

script:
  - run-prove gamebox-math.tests.asd
